version: '3.5'

services:
    identityserver0:
      image: kakoytononame15/identityserver0
      ports:
        - "5000:3000"
      container_name: identityserver0  
    eventApi:
      image: eventapi
      build: 
        context: .
        dockerfile: SenseWebApi1/Dockerfile 
      ports:
        - "5001:80"
    mongodb:
      image: mongodb/mongodb-community-server:latest
      environment:
        - MONGO_INITDB_ROOT_USERNAME=user
        - MONGO_INITDB_ROOT_PASSWORD=pass
      ports:
        - "5002:27017"